apiVersion: v1
kind: Service
metadata:
  name: kubeservice
spec:
  selector:
    app: kubeusers2
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeusers2
spec:
  replicas: 5
  selector: 
    matchLabels: 
      app: kubeusers2
  template:
    metadata:
      labels:
        app: kubeusers2
    spec:
      containers:
      - name: kubecontainer
        image: dipietrojm/server-mock-2:1.0.0
        ports:
          - containerPort: 8080
        env:
          - name: MONGO_URI
            value: 'mongodb+srv://admin:admin@cluster0.xibok.mongodb.net/coderhouse?retryWrites=true&w=majority'
        imagePullPolicy: Always